//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SokolovExamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunktVidachi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PunktVidachi()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int IDPunktVidashi { get; set; }
        public int IDCity { get; set; }
        public int AdressIndex { get; set; }
        public string Street { get; set; }
        public Nullable<int> StreetNumber { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
