//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SokolovExamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int IDTovar { get; set; }
        public int IDPostavshik { get; set; }
        public int IDProizvoditelia { get; set; }
        public int IDTovarCategory { get; set; }
        public int IDEdIzm { get; set; }
        public string Article { get; set; }
        public string TovarName { get; set; }
        public decimal Cost { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> KolvoNaSklade { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual EdIzmer EdIzmer { get; set; }
        public virtual Postavshik Postavshik { get; set; }
        public virtual Proizvoditeli Proizvoditeli { get; set; }
        public virtual TovarCategory TovarCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
