//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SokolovExamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int IDZakaza { get; set; }
        public int IDTovar { get; set; }
        public Nullable<int> IDPunktVidashi { get; set; }
        public int IDUser { get; set; }
        public Nullable<int> IDStatusZakaza { get; set; }
        public int NomerZakaza { get; set; }
        public Nullable<int> Kolvo { get; set; }
        public Nullable<System.DateTime> DateZakaza { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
        public Nullable<int> CodePolushenia { get; set; }
    
        public virtual PunktVidachi PunktVidachi { get; set; }
        public virtual StatusZakaza StatusZakaza { get; set; }
        public virtual Tovar Tovar { get; set; }
        public virtual User User { get; set; }
    }
}
